name: Test deploy
on:
  workflow_dispatch:
  push:
    branches:
      - test-branch

jobs:
  gnu-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install x86_64-unknown-linux-gnu target
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: Build mbdook-katex
        run: |
          cargo build --release
      - name: Move
        run: |
          mv target/release/mdbook-katex mdbook-katex
      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          path: mdbook-katex

  binary-exec:
    needs: [gnu-linux-binary]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          path: mdbook-katex
      - name: Exec
        run: >
          ls -la
          ./mdbook-katex/mdbook-katex --version
